name: Ruby Gem test and build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}  
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', head, jruby, jruby-head, truffleruby, truffleruby-head]
    steps:
    - uses: actions/checkout@v4
    - name: Install icu-devtools on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install -y icu-devtools
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the test suit
      run: bundle exec rake
